#!groovy

// Generated by IBM TransformationAdvisor
// Tue Apr 02 15:42:15 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}